#!/bin/bash

hda=/home/liam/qemu/x86_64/windows-bootstrap/win7.qcow2
#cdrom="-cdrom /home/liam/qemu/x86_64/virtio/installer7.iso"

sudo qemu-system-x86_64 --enable-kvm -daemonize \
    -m 2048 -hda $hda $cdrom -net nic -net user \
    -rtc base=localtime,clock=host -soundhw ac97 \
    -vga std 2>/home/liam/qemu/errors
# -vnc unix:/home/liam/.qemu-myvm-vnc
# -nographic -vnc :0
# http://blog.scottlowe.org/2013/08/21/accessing-vnc-consoles-of-kvm-guests-via-ssh/
