#!/bin/bash

wifi() {
    sudo ifdown --force wlan0 && sudo ifup wlan0 || sudo ifup wlan0
    timeout 10s ping -c2 google.com && notify-send "Up"
}

pi() {
    ip=192.168.1.39 
    ssh-keygen -f ~/.ssh/known_hosts -R $ip && echo Removed $ip
    ssh-copy-id $ip
    ssh $ip
}

case $1 in
    wifi|pi) $1 ;;
esac
