#!/bin/bash

[[ "$1" = "stdout" ]] && exec > $1 || exec > ~/nodejs/simple/index.pug
#can redirect more than once > index2.jade
#save stdout and stderr to file descriptors 3 and 4, then redirect to index.jade
#exec 3>&1 4>&2 >index.jade 2>&1
#restore stdout and stderr

link=/home/liam/nodejs/pug/raw
mapfile -t link <$link

  cat <<EOF
doctype 5
html(lang="en")
  head
    title= 'Index of Music, sorted by Artists'
    meta(name='viewport', content='width=device-width')
    link('type="text/css" rel="stylesheet" href="style.css"')
  body
    h1 Music, sorted by Artists
    h2 Use a(href='www.koajs.com') for index.html 
EOF

for i in "${link[@]}";do
#count items in array?
x=$(echo $i | cut -c 3-)
echo    "span(style='text-align: right; padding-left: 1em;')
          a(href='$i') $x"
done 

#cat << EOF
#  br
#    address
#      | NodeJS v.4.4.7
#      | serving music on 192.168.1.38 port 8000
#EOF

