#!/bin/bash

[[ ! -z $1 ]] && pic=$1 || pic=~/Pictures/space.jpg
convert $pic -colors 16 -depth 8 -format '%c' histogram:info:- \
    | sort --reverse --numeric-sort \
    | gawk 'match ($0, /^ *[0-9]+: \([^)]+\) (#[0-9A-F]+) .+$/, a) { print a[1] }'
