#!/bin/bash

img=`awk -F"=" 'FNR == 3 {print $2}' ~/scripts/col2html/colors | sed 's/~/\/home\/liam/' `
cat << EOF
<!DOCTYPE html>
<html>
<head>
<style>
.color-sample {
   float: left;
   margin: 2px;
   width: 64px;
   height: 64px;
   border-radius: 3px;
}
</style>
</head>
<body>
<img src="$img"></img>
EOF

while read line; do
	echo "<div class=\"color-sample\" style=\"background: ${line}\"></div>"
done

cat << EOF
</body>
</html>
EOF

